export default {
    HOME: "/",
    ADMIN: "/admin",
    LOGIN: "/login",
    REGISTER: "/register",
    MOVIE_DETAIL: "/movie",
    BOOKING: "/booking",
    BLOG: "/blog",
    EVENT: "/event",
    THEATER: "/theater",
    CONTACT: "/contact",
    LIST_MOVIES: "/list-movie",
    HOTELS: "/hotel",
    TRAVEL: "/travel",
    GASTRONOMY: "/gastronomy",
    AMUSEMENT: "/amusement",
    NEWS: "/news",
    ABOUT_KARNEL: "/about-us",
    PAYMENT: "/PAYMENT",
};
